### ISSUE TITLE
Pass all go build and qc checks

### ISSUE THREAD

**Issue by yuri-norwood** [yuri-norwood/bfk#7]
* [x] #1 Go Vet: mismatched types int64 and int (#6)
* [x] #2 Go Lint: avoid using underscores in Go names in [cells.go](https://github.com/yuri-norwood/bfk/blob/0fd9c62b3171f745ca205f56b40bdf858df60733/cell.go#L3-L6) (#9)
* [x] #3 Go Lint: avoid using underscores in Go names in [tape.go](https://github.com/yuri-norwood/bfk/blob/0fd9c62b3171f745ca205f56b40bdf858df60733/tape.go#L4) (#10)
* [x] #4 Go Lint: exported type should have comment or be unexported documentation
